"""Train the tiny GPT, quantize to Q16.16, verify fixed-point generation,
then export weights (.hex) + config (config.vh) + testbench vectors."""
import os, numpy as np
import model as M
import fixed as F
from fixed_infer import FixedGPT

HERE = os.path.dirname(__file__)
ROOT = os.path.abspath(os.path.join(HERE, '..'))
WDIR = os.path.join(ROOT, 'weights')
RTL  = os.path.join(ROOT, 'rtl')
os.makedirs(WDIR, exist_ok=True); os.makedirs(RTL, exist_ok=True)

# ----- corpus -----------------------------------------------------------
TEXT = "the quick brown fox jumps over the lazy dog. " * 12
chars = sorted(set(TEXT))
stoi = {c:i for i,c in enumerate(chars)}
itos = {i:c for c,i in stoi.items()}
V = len(chars)
data = np.array([stoi[c] for c in TEXT], dtype=np.int64)

cfg = M.Config(V=V, D=32, L=2, T=24, M=64)
print(f"vocab={V} chars={''.join(chars)!r}")
print(f"config D={cfg.D} L={cfg.L} T={cfg.T} M={cfg.M}")

# ----- train (Adam) -----------------------------------------------------
np.random.seed(0)
g = M.GPT(cfg, seed=2)
m = {k: np.zeros_like(v) for k,v in g.p.items()}
v = {k: np.zeros_like(v) for k,v in g.p.items()}
lr, b1, b2, eps = 3e-3, 0.9, 0.999, 1e-8
STEPS = 4000
for step in range(1, STEPS+1):
    i = np.random.randint(0, len(data)-cfg.T-1)
    idx = data[i:i+cfg.T]; tgt = data[i+1:i+cfg.T+1]
    loss, grad = g.loss_and_grad(idx, tgt)
    for k in g.p:
        m[k] = b1*m[k] + (1-b1)*grad[k]
        v[k] = b2*v[k] + (1-b2)*grad[k]**2
        mh = m[k]/(1-b1**step); vh = v[k]/(1-b2**step)
        g.p[k] -= lr*mh/(np.sqrt(vh)+eps)
    if step % 500 == 0 or step == 1:
        print(f"step {step:5d}  loss {loss:.4f}")

# ----- quantize ---------------------------------------------------------
# matvec computes y[o]=sum_k W[o,k]*x[k] (row-major (out,in)); the float linear
# weights are (in,out), so transpose every linear weight (keys starting 'W').
q = {}
for k, val in g.p.items():
    v2 = val.T if (k[0] == 'W' and val.ndim == 2) else val
    q[k] = np.vectorize(F.to_fixed)(np.ascontiguousarray(v2).ravel()).astype(np.int64)

consts = {'INV_SQRT_D': F.to_fixed(1.0/np.sqrt(cfg.D)), 'EPS': F.to_fixed(1e-3)}
cfgd = dict(V=cfg.V, D=cfg.D, L=cfg.L, T=cfg.T, M=cfg.M)
fg = FixedGPT({k:list(map(int,v)) for k,v in q.items()}, cfgd, consts)

# ----- verify generation in fixed point ---------------------------------
prompt = [stoi[c] for c in "the "]
gen = fg.generate(prompt, cfg.T)
text = ''.join(itos[t] for t in gen)
print("\nFIXED-POINT generation:")
print(repr(text))

# float reference generation for comparison
def float_gen(prompt, T):
    seq = list(prompt)+[0]*(T-len(prompt)); cur=len(prompt); out=list(prompt)
    while cur < T:
        lg = g.forward(np.array(seq))
        nxt = int(lg[cur-1].argmax()); seq[cur]=nxt; out.append(nxt); cur+=1
    return out
ftext = ''.join(itos[t] for t in float_gen(prompt, cfg.T))
print("FLOAT     generation:", repr(ftext))

# ----- export hex weights ----------------------------------------------
def w32(x):
    x = int(x) & 0xFFFFFFFF
    return f"{x:08x}"

def dump(name, arr):
    with open(os.path.join(WDIR, name+'.hex'), 'w') as f:
        for x in np.asarray(arr).ravel():
            f.write(w32(x)+"\n")

for k, val in q.items():
    dump(k, val)

# ----- config.vh --------------------------------------------------------
def hx(x): return f"32'h{(int(x)&0xFFFFFFFF):08x}"
lines = []
lines.append("// Auto-generated by ref/train_and_export.py -- do not edit.")
lines.append(f"`define VOCAB {cfg.V}")
lines.append(f"`define DMODEL {cfg.D}")
lines.append(f"`define NLAYER {cfg.L}")
lines.append(f"`define SEQLEN {cfg.T}")
lines.append(f"`define DFF {cfg.M}")
lines.append(f"`define WBITS {F.W}")
lines.append(f"`define FRAC {F.FRAC}")
lines.append(f"`define INV_SQRT_D {hx(consts['INV_SQRT_D'])}")
lines.append(f"`define EPS_Q {hx(consts['EPS'])}")
lines.append(f"`define LOG2E {hx(F.LOG2E)}")
lines.append(f"`define EXP_P0 {hx(F.P0)}")
lines.append(f"`define EXP_P1 {hx(F.P1)}")
lines.append(f"`define EXP_P2 {hx(F.P2)}")
lines.append(f"`define EXP_P3 {hx(F.P3)}")
lines.append(f"`define PROMPT_LEN {len(prompt)}")
with open(os.path.join(RTL, 'config.vh'), 'w') as f:
    f.write("\n".join(lines)+"\n")

# id -> ascii helper (included inside the testbench module)
al = ["// Auto-generated id->ascii decoder.",
      "function [7:0] id2asc; input integer id; begin case(id)"]
for i,c in itos.items():
    al.append(f"  {i}: id2asc = 8'd{ord(c)};")
al.append("  default: id2asc = 8'd63; endcase end endfunction")
with open(os.path.join(RTL, 'id2asc.vh'), 'w') as f:
    f.write("\n".join(al)+"\n")

# ----- load_weights.vh ($readmemh statements) ---------------------------
D, Mh, L = cfg.D, cfg.M, cfg.L
lw = ["// Auto-generated -- $readmemh weight loads."]
def rd(f, mem, s=None, e=None):
    if s is None: lw.append(f'  $readmemh("weights/{f}.hex", {mem});')
    else:         lw.append(f'  $readmemh("weights/{f}.hex", {mem}, {s}, {e});')
rd('tok','tok_mem'); rd('pos','pos_mem')
rd('lnfg','lnfg_mem'); rd('lnfb','lnfb_mem')
rd('Wh','Wh_mem'); rd('bh','bh_mem')
for l in range(L):
    rd(f'Wq{l}','Wq_mem', l*D*D, (l+1)*D*D-1)
    rd(f'Wk{l}','Wk_mem', l*D*D, (l+1)*D*D-1)
    rd(f'Wv{l}','Wv_mem', l*D*D, (l+1)*D*D-1)
    rd(f'Wo{l}','Wo_mem', l*D*D, (l+1)*D*D-1)
    rd(f'W1{l}','W1_mem', l*Mh*D, (l+1)*Mh*D-1)
    rd(f'W2{l}','W2_mem', l*D*Mh, (l+1)*D*Mh-1)
    for nm in ['bq','bk','bv','bo','ln1g','ln1b','ln2g','ln2b','b2']:
        rd(f'{nm}{l}', f'{nm}_mem', l*D, (l+1)*D-1)
    rd(f'b1{l}','b1_mem', l*Mh, (l+1)*Mh-1)
with open(os.path.join(RTL,'load_weights.vh'),'w') as f:
    f.write("\n".join(lw)+"\n")

# ----- testbench vectors (prompt + golden tokens) -----------------------
with open(os.path.join(WDIR, 'prompt.hex'), 'w') as f:
    for t in prompt: f.write(w32(t)+"\n")
with open(os.path.join(WDIR, 'golden.hex'), 'w') as f:
    for t in gen: f.write(w32(t)+"\n")
with open(os.path.join(ROOT, 'build', 'golden.txt'), 'w') as f:
    f.write(text+"\n")

# ----- metadata (for ref/gen.py) ----------------------------------------
import json
meta = dict(cfg=cfgd, consts={k:int(v) for k,v in consts.items()},
            stoi=stoi, itos={str(k):v for k,v in itos.items()},
            names=list(q.keys()))
with open(os.path.join(WDIR,'meta.json'),'w') as f:
    json.dump(meta, f)

print("\nExported weights to", WDIR)
print("Exported config to", os.path.join(RTL,'config.vh'))
