// Auto-generated by ref/train_and_export.py -- do not edit.
`define VOCAB 28
`define DMODEL 32
`define NLAYER 2
`define SEQLEN 24
`define DFF 64
`define WBITS 32
`define FRAC 16
`define INV_SQRT_D 32'h00002d41
`define EPS_Q 32'h00000042
`define LOG2E 32'h00017154
`define EXP_P0 32'h00010000
`define EXP_P1 32'h0000b172
`define EXP_P2 32'h00003d7f
`define EXP_P3 32'h00000e36
`define PROMPT_LEN 4
